"""media assets

Revision ID: df947d7fc255
Revises: dc6cbfda0ff5
Create Date: 2026-07-27 06:07:46.955685

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "df947d7fc255"
down_revision: str | None = "dc6cbfda0ff5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "media_assets",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum("lesson_video", "course_cover", "lesson_attachment", name="media_kind"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("pending", "ready", "failed", name="media_status"),
            server_default="pending",
            nullable=False,
        ),
        sa.Column("storage_key", sa.String(length=512), nullable=False),
        sa.Column("original_filename", sa.String(length=255), nullable=False),
        sa.Column("content_type", sa.String(length=127), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=True),
        sa.Column("checksum", sa.String(length=128), nullable=True),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("uploaded_by", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(status <> 'ready') OR (confirmed_at IS NOT NULL AND size_bytes IS NOT NULL)",
            name=op.f("ck_media_assets_ready_is_confirmed"),
        ),
        sa.CheckConstraint(
            "size_bytes IS NULL OR size_bytes >= 0", name=op.f("ck_media_assets_size_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["uploaded_by"],
            ["user_profiles.user_id"],
            name=op.f("fk_media_assets_uploaded_by_user_profiles"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_media_assets")),
        sa.UniqueConstraint("storage_key", name=op.f("uq_media_assets_storage_key")),
    )
    op.create_index(
        "ix_media_assets_status_created_at", "media_assets", ["status", "created_at"], unique=False
    )
    op.create_index("ix_media_assets_uploaded_by", "media_assets", ["uploaded_by"], unique=False)
    op.add_column("courses", sa.Column("cover_asset_id", sa.UUID(), nullable=True))
    op.create_foreign_key(
        op.f("fk_courses_cover_asset_id_media_assets"),
        "courses",
        "media_assets",
        ["cover_asset_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.drop_column("courses", "cover_image_key")
    op.add_column("lessons", sa.Column("video_asset_id", sa.UUID(), nullable=True))
    op.create_foreign_key(
        op.f("fk_lessons_video_asset_id_media_assets"),
        "lessons",
        "media_assets",
        ["video_asset_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_lessons_video_asset_id_media_assets"), "lessons", type_="foreignkey"
    )
    op.drop_column("lessons", "video_asset_id")
    op.add_column(
        "courses",
        sa.Column("cover_image_key", sa.VARCHAR(length=512), autoincrement=False, nullable=True),
    )
    op.drop_constraint(
        op.f("fk_courses_cover_asset_id_media_assets"), "courses", type_="foreignkey"
    )
    op.drop_column("courses", "cover_asset_id")
    op.drop_index("ix_media_assets_uploaded_by", table_name="media_assets")
    op.drop_index("ix_media_assets_status_created_at", table_name="media_assets")
    op.drop_table("media_assets")
    # ### end Alembic commands ###
