"""course catalogue

Revision ID: dc6cbfda0ff5
Revises: 0001_auth_foundation
Create Date: 2026-07-26 13:19:04.715986

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "dc6cbfda0ff5"
down_revision: str | None = "0001_auth_foundation"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "courses",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("slug", sa.String(length=160), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("subtitle", sa.String(length=300), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("specialty", sa.String(length=120), nullable=True),
        sa.Column(
            "difficulty",
            sa.Enum("foundation", "intermediate", "advanced", name="course_difficulty"),
            server_default="foundation",
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("draft", "published", "archived", name="content_status"),
            server_default="draft",
            nullable=False,
        ),
        sa.Column("cover_image_key", sa.String(length=512), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(status <> 'published') OR (published_at IS NOT NULL)",
            name=op.f("ck_courses_published_has_timestamp"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["user_profiles.user_id"],
            name=op.f("fk_courses_created_by_user_profiles"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_courses")),
        sa.UniqueConstraint("id", name="uq_courses_id"),
        sa.UniqueConstraint("slug", name=op.f("uq_courses_slug")),
    )
    op.create_index("ix_courses_specialty", "courses", ["specialty"], unique=False)
    op.create_index(
        "ix_courses_status_published_at", "courses", ["status", "published_at"], unique=False
    )
    op.create_table(
        "modules",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("course_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("position >= 0", name=op.f("ck_modules_position_non_negative")),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["courses.id"],
            name=op.f("fk_modules_course_id_courses"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_modules")),
        sa.UniqueConstraint(
            "course_id",
            "position",
            deferrable=True,
            initially="DEFERRED",
            name="uq_modules_course_id_position",
        ),
        sa.UniqueConstraint("id", "course_id", name="uq_modules_id_course_id"),
    )
    op.create_index(
        "ix_modules_course_id_position", "modules", ["course_id", "position"], unique=False
    )
    op.create_table(
        "lessons",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("module_id", sa.UUID(), nullable=False),
        sa.Column("course_id", sa.UUID(), nullable=False),
        sa.Column("slug", sa.String(length=160), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column(
            "content_type",
            sa.Enum("video", "reading", "quiz", name="lesson_content_type"),
            server_default="video",
            nullable=False,
        ),
        sa.Column("duration_seconds", sa.Integer(), nullable=True),
        sa.Column("is_free_preview", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "status",
            sa.Enum("draft", "published", "archived", name="content_status"),
            server_default="draft",
            nullable=False,
        ),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "duration_seconds IS NULL OR duration_seconds > 0",
            name=op.f("ck_lessons_duration_positive"),
        ),
        sa.CheckConstraint("position >= 0", name=op.f("ck_lessons_position_non_negative")),
        sa.ForeignKeyConstraint(
            ["module_id", "course_id"],
            ["modules.id", "modules.course_id"],
            name="fk_lessons_module_id_course_id_modules",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_lessons")),
        sa.UniqueConstraint("course_id", "slug", name="uq_lessons_course_id_slug"),
        sa.UniqueConstraint(
            "module_id",
            "position",
            deferrable=True,
            initially="DEFERRED",
            name="uq_lessons_module_id_position",
        ),
    )
    op.create_index("ix_lessons_course_id_status", "lessons", ["course_id", "status"], unique=False)
    op.create_index(
        "ix_lessons_module_id_position", "lessons", ["module_id", "position"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_lessons_module_id_position", table_name="lessons")
    op.drop_index("ix_lessons_course_id_status", table_name="lessons")
    op.drop_table("lessons")
    op.drop_index("ix_modules_course_id_position", table_name="modules")
    op.drop_table("modules")
    op.drop_index("ix_courses_status_published_at", table_name="courses")
    op.drop_index("ix_courses_specialty", table_name="courses")
    op.drop_table("courses")
    # ### end Alembic commands ###
